# Generated by Django 3.1.4 on 2021-04-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca_produto', models.CharField(max_length=30, verbose_name='Marca:')),
                ('forn_marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.fornecedor')),
            ],
            options={
                'db_table': 'marca',
                'ordering': ('marca_produto',),
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('estoq', models.IntegerField(verbose_name='estoque atual')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(blank=True, null=True)),
                ('observacoes', models.CharField(max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.marca')),
            ],
            options={
                'db_table': 'produto',
                'ordering': ('nome',),
            },
        ),
    ]
