# Generated by Django 3.1.4 on 2021-04-02 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('created', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('cod_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nf', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota fiscal')),
                ('movimento', models.CharField(blank=True, choices=[('e', 'entrada'), ('s', 'saida')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor R$:')),
                ('obs', models.CharField(max_length=200, verbose_name='Observações:')),
                ('forn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.fornecedor')),
                ('funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compras',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('movimento', models.CharField(blank=True, choices=[('e', 'entrada'), ('s', 'saida')], max_length=1)),
                ('funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EstoqueItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField(blank=True)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='estoque.estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ComprasItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.PositiveIntegerField()),
                ('sald', models.PositiveIntegerField(blank=True, verbose_name='Saldo no Estoque')),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total dos Itens')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='estoque.compras')),
                ('produtos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ComprasEntrada',
            fields=[
            ],
            options={
                'verbose_name': 'compra entrada',
                'verbose_name_plural': 'compra entrada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.compras',),
        ),
        migrations.CreateModel(
            name='EstoqueEntrada',
            fields=[
            ],
            options={
                'verbose_name': 'estoque entrada',
                'verbose_name_plural': 'estoque entrada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.estoque',),
        ),
    ]
