# Generated by Django 3.1.4 on 2021-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='estoqueitens',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='estoqueitens',
            name='produto',
        ),
        migrations.DeleteModel(
            name='EstoqueEntrada',
        ),
        migrations.AlterField(
            model_name='compras',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da NF R$:'),
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='EstoqueItens',
        ),
    ]
